batch_size:
min: 1024
max: -1
type: int
log_space: True
learning_rate:
max: 10.0
min: 1.0e-3
type: float
log_space: True
max_grad_norm:
max: 10.0
min: 1.0e-3
type: float
log_space: True
clip_bound_lower_bound:
max: 10
min: 1.0e-3
type: float
log_space: True
